stages:
  - test
  - deploy

test:
  stage: test
    tags:
      - APP
    script: |
      '='*64
      New-Object -TypeName PSCustomObject -Property $PSVersionTable | ft PSVersion,PSEdition
      '-'*32
      'Env:'
      ls env:\*
      '-'*32
      'Global:'
      Get-Variable -Name * | select Name,@{n='Value';e={ConvertTo-Json -Compress $_.Value -Depth 2 -WarningAction SilentlyContinue}} | ft -a
      '-'*32
      '='*64

deploy_to_iis:
  stage: deploy
  tags:
    - APP
  only:
    - main
  script: |
    chcp 65001
    $WEB_SITE = 'PowerShellWebService'
    $APP_POOL = 'PowerShellWebService'
    $APP_PATH = 'C:\inetpub\PowerShellWebService'
    $LOCATION = Get-Location
    (Get-Date).ToString('o')
    New-Object -TypeName PSCustomObject -Property $PSVersionTable | ft PSVersion,PSEdition,OS
    dotnet.exe build
    Import-Module WebAdministration -WarningAction:SilentlyContinue
    Get-WebSite -Name $WEB_SITE | ft Id,Name,State
    Write-Host $LOCATION -ForegroundColor Yellow
    Get-ChildItem -Path $LOCATION -Recurse | Group-Object -Property Directory | Select-Object -Property @{n='Directory';e={$_.Name.replace($LOCATION,'')}},Count
    Stop-WebSite -Name $WEB_SITE -Passthru | ft Id,Name,State
    Stop-WebAppPool -Name $APP_POOL -Passthru | ft Name,State
    try {Copy-Item -Force -Recurse -Path "$LOCATION\bin\Debug\net7.0-windows\*" -Destination "$APP_PATH" -Exclude @('appsettings.json','web.config')} catch {Write-Warning $_.Exception}
    try {Copy-Item -Force -Recurse -Path "$LOCATION\wwwroot\*" -Destination "$APP_PATH\wwwroot"} catch {Write-Warning $_.Exception}
    try {Copy-Item -Force -Recurse -Path "$LOCATION\.scripts\*" -Destination "$APP_PATH\.scripts"} catch {Write-Warning $_.Exception}
    Start-WebAppPool -Name $APP_POOL -Passthru | ft Name,State
    Start-WebSite -Name $WEB_SITE -Passthru | ft Id,Name,State
    (Get-Date).ToString('o')
