stages:
  - deploy

deploy_to_repository:
  stage: deploy
  only:
    - main
  script: 
   - chcp 65001
   - whoami.exe
   - New-Object -TypeName PSCustomObject -Property $PSVersionTable | ft PSVersion,PSEdition,OS
   - (Get-Date).ToString('o')
   - $Location = Get-Location
   - dotnet.exe build
   - Import-Module WebAdministration -WarningAction:SilentlyContinue
   - Get-WebSite -Name 'PowerShellWebService' | ft Id,Name,State,Bindings
   - Write-Host $Location -ForegroundColor Yellow
   - Get-ChildItem -Path $Location -Recurse | % {$_.FullName.replace($Location,'')}
   - Stop-WebSite -Name 'PowerShellWebService' -Passthru | ft Id,Name,State,Bindings
   - Stop-WebAppPool -Name 'PowerShellWebService' -Passthru | ft Name,State,Applications
   - try {Copy-Item -Force -Recurse -Path "$Location\bin\Debug\net7.0-windows\*" -Destination 'C:\inetpub\PowerShellWebService\'} catch {Write-Warning $_.Exception}
   - Start-WebAppPool -Name 'PowerShellWebService' -Passthru | ft Name,State,Applications
   - Start-WebSite -Name 'PowerShellWebService' -Passthru | ft Id,Name,State,Bindings
   - (Get-Date).ToString('o')
  tags: 
    - APP
